- name: Install dependencies for Kubernetes and Docker
  hosts: Slave_node
  become: yes
  tasks:

    - name: Disable swap
      ansible.builtin.command: swapoff -a

    - name: Remove swap entry from fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(^.*swap.*$)'
        replace: '# \1'

#    - name: Update apt package list
#      ansible.builtin.apt:
#        update_cache: yes

    # ---------- DOCKER SETUP ----------
    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | default('jammy') }} stable"
        filename: docker

#    - name: Update apt after Docker repo add
#      ansible.builtin.apt:
#        update_cache: yes

    - name: Install Docker engine and CLI
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started

    # ---------- KUBERNETES SETUP ----------
    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: Add Kubernetes APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        filename: kubernetes

#    - name: Update apt after Kubernetes repo add
#      ansible.builtin.apt:
#        update_cache: yes

    - name: Install kubeadm, kubelet, and kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kube packages
      ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl

